org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official

org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true

#MPP
kotlin.mpp.enableCInteropCommonization=true

#Native
kotlin.native.ignoreDisabledTargets=true

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

user=OmyDaGreat
repo=MaleficComponents
g=xyz.malefic.compose
artifact=comps
desc=A Compose Desktop library containing useful UI elements and components

v=2.1.1